version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    products-api:
        build:
            context: .
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb://mongodb:27017/products-api-db
            JWT_SECRET: your-secret-key
