version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
        command: mongod --quiet --logpath /dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/products-api-db --quiet
            interval: 10s
            timeout: 2s
            retries: 5
            start_period: 5s
        restart: always
        volumes:
            - mongodata:/data/db
        networks:
            - products-api-network

    products-api:
        build:
            context: .
        env_file:
            - docker-compose.env
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - mongodb
        volumes:
            - logs:/app/logs
            - /app/node_modules
        networks:
            - products-api-network

networks:
    products-api-network:
        driver: bridge

volumes:
    mongodata:
    logs:
