version: '3'
services:
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./data:/data/db
        command: mongod --quiet --logpath /dev/null
        networks:
            - products-api-network

    products-api:
        build:
            context: .
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb://mongodb:27017/products-api-db
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - products-api-network

networks:
    products-api-network:
        driver: bridge
